name: actions

on:
  push:
  pull_request:

jobs:
  linux-tests:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, fileinfo, ftp, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress --prefer-stable
          
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit

  phpstan:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, gd, pdo_mysql, fileinfo, ftp, memcached
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-progress --prefer-stable
          
      - name: run phpstan
        run: vendor/bin/phpstan

